export default [
    {
        id:0,
        img:"/product__1.webp",
        name:"Wild Silk Finish Lipstick",
        price: 41.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:1,
        img:"/product__2.webp",
        name:"Wild Silk Finish Lipstick",
        price: 41.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:2,
        img:"/product__3.webp",
        name:"Wild Silk Finish Lipstick",
        price: 41.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:3,
        img:"/product__4.webp",
        name:"Wild Silk Finish Lipstick",
        price: 41.0,
        category:["lipsticks", "makeup"],
        sale:true,
    },
    {
        id:4,
        img:"/product__5.webp",
        name:"Goat Milk Lotion For Body",
        price: 15.0,
        category:["skin care"],
        sale:false,
    },
    {
        id:5,
        img:"/product__6.webp",
        name:"Lead Gel Nail Polish",
        price: 18.0,
        category:["nail & wax"],
        sale:false,
    },
    {
        id:6,
        img:"/product__7.webp",
        name:"Lead Gel Nail Polish",
        price: 18.0,
        category:["nail & wash"],
        sale:true,
    },
    {
        id:7,
        img:"/product__8.webp",
        name:"Lead Gel Nail Polish",
        price: 18.0,
        category:["nail & wax"],
        sale:false,
    },
    {
        id:8,
        img:"/product__9.webp",
        name:"Lead Gel Nail Polish",
        price: 18.0,
        category:["nail & wax"],
        sale:false,
    },
    {
        id:9,
        img:"/product__11.webp",
        name:"Washablle Bold Eye Mascare",
        price: 55.0,
        category:["makeup"],
        sale:true,
    },
    {
        id:10,
        img:"/product__12.webp",
        name:"Washablle Bold Eye Mascare",
        price: 55.0,
        category:["makeup"],
        sale:false,
    },
    {
        id:11,
        img:"/product__13.webp",
        name:"Cleanser with Salicylic Acid",
        price: 16.0,
        category:["skin care"],
        sale:false,
    },
    {
        id:12,
        img:"/product__14.webp",
        name:"Xtreme Wear Nail Polish",
        price: 55.0,
        category:["makeup","nail & wax"],
        sale:true,
    },
    {
        id:13,
        img:"/product__15.webp",
        name:"Xtreme Wear Nail Polish",
        price: 55.0,
        category:["makeup","nail & wax"],
        sale:false,
    },
    {
        id:14,
        img:"/product__16.webp",
        name:"Xtreme Wear Nail Polish",
        price: 55.0,
        category:["makeup", "nail & wax"],
        sale:false,
    },
    {
        id:15,
        img:"/product__17.webp",
        name:"Xtreme Wear Nail Polish",
        price: 55.0,
        category:["makeup","nail & wax"],
        sale:true,
    },
    {
        id:16,
        img:"/product__18.webp",
        name:"Glam Liquid Eyeshadow",
        price: 16.0,
        category:["makeup"],
        sale:false,
    },
    {
        id:17,
        img:"/product__19.webp",
        name:"Glam Liquid Eyeshadow",
        price: 16.0,
        category:["makeup"],
        sale:true,
    },
    {
        id:18,
        img:"/product__20.webp",
        name:"Glam Liquid Eyeshadow",
        price: 16.0,
        category:["makeup"],
        sale:false,
    },
    {
        id:19,
        img:"/product__21.webp",
        name:"Glam Liquid Eyeshadow",
        price: 16.0,
        category:["makeup"],
        sale:false,
    },
    {
        id:20,
        img:"/product__22.webp",
        name:"NYX Matte Lipstick",
        price: 25.0,
        category:["makeup","lipsticks"],
        sale:true,
    },
    {
        id:21,
        img:"/product__23.webp",
        name:"Baby Oil",
        price: 20.0,
        category:["skin care"],
        sale:false,
    },
    {
        id:22,
        img:"/product__24.webp",
        name:"Hansen Vitamin C cleaneser",
        price: 15.5,
        category:["skin care"],
        sale:false,
    },
    {
        id:23,
        img:"/product__25.webp",
        name:"Arabica Coffee Scrub Skin",
        price: 18.0,
        category:["skin care"],
        sale:true,
    },
    {
        id:24,
        img:"/product__26.webp",
        name:"Rose Massage Oil",
        price: 25.0,
        category:["skin care"],
        sale:false,
    },
    {
        id:25,
        img:"/product__27.webp",
        name:"Secret Tease Candy Noir",
        price: 12.0,
        category:["makeup"],
        sale:false,
    },
    {
        id:26,
        img:"/product__28.webp",
        name:"Gloss Pink with Collagen",
        price: 29.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:27,
        img:"/product__29.webp",
        name:"Gloss Pink with Collagen",
        price: 29.0,
        category:["lipsticks"],
        sale:true,
    },
    {
        id:28,
        img:"/product__30.webp",
        name:"Minerals Matte Lipstick",
        price: 43.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:29,
        img:"/product__31.webp",
        name:"Minerals Matte Lipstick",
        price: 41.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:30,
        img:"/product__32.webp",
        name:"Minerals Matte Lipstick",
        price: 43.0,
        category:["lipsticks"],
        sale:true,
    },
    {
        id:31,
        img:"/product__33.webp",
        name:"Natural Tea Body Wash",
        price: 41.0,
        category:["lipsticks"],
        sale:false,
    },
    {
        id:32,
        img:"/product__34.webp",
        name:"Touch Keratosis Pilaris",
        price: 29.0,
        category:["skin care"],
        sale:false,
    },
    {
        id:33,
        img:"/product__35.webp",
        name:"Yves Saint Laurent Libre",
        price: 23.0,
        category:["makeup"],
        sale:false,
    },
];